name: Dependabot Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at 00:00 UTC

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot updates
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
